esphome:
  name: device1
  # friendly_name: 'HVAC Input Pressure Sensor HV210' 
  # name_add_mac_suffix: true
  
esp32:
  board: esp32-s3-devkitc1-n16r8
  framework:                                                                            
    type: esp-idf
wifi:
  ssid: "your_SSID"
  password: "your_PASSWORD"
  fast_connect: true
# Point to your local component directory
external_components:
  - source:
      type: local
      path: ../components
    components: [hvxxx]

# Standard I2C setup
i2c:
  id: bus_a
  sda: GPIO10
  scl: GPIO11
  scan: True
  frequency: 100kHz
 
# Your component's configuration
sensor: 
  - platform: hvxxx
    id: hvac_pressure_sensor_input_1
    name: "HVAC Input Pressure Sensor" 

    i2c_id: bus_a 
    address: 0x28  # I2C address of the sensor; default is usually 0x28
    model: HV210  # Model is the chip family; used for validation & C++ model check
    pressure_range: 1inh2o 
    bandwidth_limit: 10hz 
    update_interval: 0.5s # Should be set to at least 3x bandwidth limit time period (e.g. 10hz -> 100ms -> 3x = 300ms)
    
    pressure: 
      name: "HVAC Input Pressure"
    
    temperature:    # If provided then temperature sensor is created and temperature readings are published
      name: "HVAC Input Temperature"